# Generated by Django 4.0.2 on 2022-03-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_brand_brand_name'),
        ('store', '0003_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
        ),
    ]
