# Generated by Django 4.0.2 on 2022-03-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
