# Generated by Django 4.0.2 on 2022-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cartitem_variations'),
        ('store', '0012_auto_20220402_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
