# Generated by Django 4.0.2 on 2022-03-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_brand_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
