# Generated by Django 3.2.9 on 2022-04-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20220402_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
